import './preloader'
import './navigation_opacity'
import './progress_page_bar'
import './text_animate'
import './mobile_menu'
import './scroll'
import './slider'
import './validation_phone'
import '../img/svg/Oleg_Ershov_logo_orange_1.svg'
// import '../css/normalize.css'
import '../css/style.css'
import '../sass/style.sass'
// import '../index.html'
// import html from '../index.html';
